import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [{ type: "autogenerated", dirName: "." }],
  languageSidebar: [{ type: "autogenerated", dirName: "language" }], // tự động gen sidebar theo dirName
  javascriptSidebar: [
    { type: "autogenerated", dirName: "language/javascript" },
  ],
  htmlCssSidebar: [{ type: "autogenerated", dirName: "language/html-css" }],
  mongoDBSidebar: [{ type: "autogenerated", dirName: "database/mongodb" }],
  sqlSidebar: [{ type: "autogenerated", dirName: "database/sql" }],
  vueJsSidebar: [{ type: "autogenerated", dirName: "framework/vuejs" }],
  googleProjectSidebar: [{ type: "autogenerated", dirName: "framework/google-project" }],
  // languageSidebar: [
  //   {
  //     type: "category",
  //     label: "Languages",
  //     items: [
  //       {
  //         type: "category",
  //         label: "JavaScript",
  //         items: [{ type: "autogenerated", dirName: "language/javascript" }],
  //       },
  //       {
  //         type: "category",
  //         label: "HTML-CSS",
  //         items: [{ type: "autogenerated", dirName: "language/html-css" }],
  //       },
  //     ],
  //   },
  // ],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   // "intro",
  //   // "hello",
  //   {
  //     type: "category",
  //     label: "Tutorial",
  //     items: ["tutorial-basics/create-a-document"],
  //   },
  // ],
};

export default sidebars;
